[build]
  functions = "functions/"

[template.environment]
  BASE_URL = "Base URL e.g. https://example.com"
  BUILD_BYPASS_KEY = "Build bypass key sent as X-IDP-Build-Key"

[[redirects]]
  from = "/print/*"
  to = "/.netlify/functions/print/:splat"
  status = 200

[[redirects]]
  from = "/screenshot/*"
  to = "/.netlify/functions/screenshot/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/screenshot/:splat"
  status = 301
